import { getClient } from './config/database.js'

export async function runMigration(c) {
const client = getClient(c.env)
try {
await client.connect()

// 1. Drop existing tables in correct dependency order
await client.query('DROP TABLE IF EXISTS assignments CASCADE')
await client.query('DROP TABLE IF EXISTS class_members CASCADE')
await client.query('DROP TABLE IF EXISTS classes CASCADE')
await client.query('DROP TABLE IF EXISTS achievements CASCADE')
await client.query('DROP TABLE IF EXISTS progress CASCADE')
await client.query('DROP TABLE IF EXISTS users CASCADE')
await client.query('DROP TABLE IF EXISTS lessons CASCADE')
await client.query('DROP TABLE IF EXISTS chapters CASCADE')
await client.query('DROP TABLE IF EXISTS courses CASCADE')
await client.query('DROP TABLE IF EXISTS categories CASCADE')
await client.query('DROP TABLE IF EXISTS learning_materials CASCADE')

// 2. Create tables
await client.query(`CREATE TABLE categories (
id BIGSERIAL PRIMARY KEY,
slug TEXT UNIQUE NOT NULL,
name_id TEXT NOT NULL,
name_en TEXT NOT NULL,
description_id TEXT,
description_en TEXT
)`)

await client.query(`CREATE TABLE courses (
id BIGSERIAL PRIMARY KEY,
slug TEXT UNIQUE NOT NULL,
category_slug TEXT REFERENCES categories(slug) ON DELETE CASCADE,
title_id TEXT NOT NULL,
title_en TEXT NOT NULL,
description_id TEXT,
description_en TEXT,
image_url TEXT,
sorting_order INT DEFAULT 1,
icon_url TEXT,
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW()
)`)

await client.query(`CREATE TABLE chapters (
id BIGSERIAL PRIMARY KEY,
slug TEXT UNIQUE NOT NULL,
course_slug TEXT REFERENCES courses(slug) ON DELETE CASCADE,
level INT NOT NULL,
title_id TEXT NOT NULL,
title_en TEXT NOT NULL,
UNIQUE (course_slug, level)
)`)

await client.query(`CREATE TABLE lessons (
id BIGSERIAL PRIMARY KEY,
slug TEXT NOT NULL,
course_slug TEXT REFERENCES courses(slug) ON DELETE CASCADE,
chapter_slug TEXT REFERENCES chapters(slug) ON DELETE SET NULL,
lesson_order INT DEFAULT 1,
language TEXT NOT NULL DEFAULT 'id',
title TEXT NOT NULL,
summary TEXT,
blocks JSONB NOT NULL DEFAULT '[]',
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW(),
UNIQUE (slug, language)
)`)

await client.query('CREATE INDEX IF NOT EXISTS idx_lessons_slug ON lessons(slug)')
await client.query('CREATE INDEX IF NOT EXISTS idx_lessons_language ON lessons(language)')
await client.query('CREATE INDEX IF NOT EXISTS idx_lessons_course ON lessons(course_slug)')
await client.query('CREATE INDEX IF NOT EXISTS idx_lessons_chapter ON lessons(chapter_slug)')

// Legacy table kept for table-existence checks (unused but keeps old queries safe)
await client.query(`CREATE TABLE learning_materials (
id BIGSERIAL PRIMARY KEY,
title VARCHAR(255) NOT NULL UNIQUE,
description VARCHAR(255) NOT NULL,
sub_materials JSONB DEFAULT NULL, 
sub_body_materials JSONB DEFAULT NULL,
learning_image_path VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW()
)`)

await client.query(`CREATE TABLE users (
id BIGSERIAL PRIMARY KEY,
firebase_uid TEXT UNIQUE NOT NULL,
display_name TEXT NOT NULL DEFAULT '',
email TEXT,
role TEXT NOT NULL DEFAULT 'student' CHECK (role IN ('student', 'teacher')),
avatar_url TEXT,
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW()
)`)

await client.query(`CREATE TABLE progress (
id BIGSERIAL PRIMARY KEY,
user_id INT REFERENCES users(id) ON DELETE CASCADE,
lesson_slug TEXT NOT NULL,
score INT DEFAULT 0,
completed_at TIMESTAMP,
UNIQUE (user_id, lesson_slug)
)`)

await client.query(`CREATE TABLE achievements (
id BIGSERIAL PRIMARY KEY,
user_id INT REFERENCES users(id) ON DELETE CASCADE,
badge_id TEXT NOT NULL,
unlocked_at TIMESTAMP DEFAULT NOW(),
UNIQUE (user_id, badge_id)
)`)

await client.query(`CREATE TABLE classes (
id BIGSERIAL PRIMARY KEY,
name TEXT NOT NULL,
owner_teacher_id INT REFERENCES users(id),
join_code TEXT UNIQUE NOT NULL,
created_at TIMESTAMP DEFAULT NOW()
)`)

await client.query(`CREATE TABLE class_members (
class_id INT REFERENCES classes(id) ON DELETE CASCADE,
user_id INT REFERENCES users(id) ON DELETE CASCADE,
role TEXT NOT NULL DEFAULT 'student' CHECK (role IN ('student', 'teacher', 'assistant')),
PRIMARY KEY (class_id, user_id)
)`)

await client.query(`CREATE TABLE assignments (
id BIGSERIAL PRIMARY KEY,
class_id INT REFERENCES classes(id) ON DELETE CASCADE,
lesson_slug TEXT NOT NULL,
title TEXT NOT NULL DEFAULT '',
due_at TIMESTAMP,
created_at TIMESTAMP DEFAULT NOW()
)`)

// 3. Seed Categories
await client.query(`INSERT INTO categories (slug, name_id, name_en, description_id, description_en) VALUES
('ai', 'AI', 'AI', 'Pahami konsep dasar bagaimana kecerdasan buatan bekerja.', 'Deepen your knowledge of how AI works.'),
('coding', 'Coding', 'Coding', 'Belajar pemrograman dasar dengan cara yang menyenangkan.', 'Learn programming concepts step-by-step.'),
('data', 'Data', 'Data', 'Eksplorasi bagaimana data melatih kecerdasan buatan.', 'Explore how data powers modern AI.'),
('cnn', 'CNN', 'CNN', 'Bagaimana komputer melihat dan mengenali gambar di sekitarnya.', 'How machines see and recognize images.')
`)

// 4. Seed Courses
await client.query(`INSERT INTO courses (slug, category_slug, title_id, title_en, description_id, description_en, image_url, sorting_order, icon_url) VALUES
('intro-to-ai', 'ai', 'Dasar Kecerdasan Buatan', 'Basic Artificial Intelligence', 'Pahami konsep dasar bagaimana kecerdasan buatan bekerja di sekitar kita.', 'Understand the basic concepts of how artificial intelligence works around us.', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600', 1, 'https://img.icons8.com/color/96/artificial-intelligence.png'),
('how-ai-learns-course', 'ai', 'Bagaimana AI Belajar', 'How AI Learns', 'Mempelajari cara melatih kecerdasan buatan dengan data dan mengenal Jaringan Saraf Tiruan.', 'Learn how to train artificial intelligence with data and explore Neural Networks.', 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?w=600', 2, 'https://img.icons8.com/color/96/neural-network.png'),
('generative-ai-course', 'ai', 'AI Generatif & Kreativitas', 'Generative AI & Creativity', 'Menjelajahi cara kerja AI generatif dalam menyusun teks, gambar, dan karya kreatif.', 'Explore how generative AI works in generating text, images, and creative works.', 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600', 3, 'https://img.icons8.com/color/96/creative-commons.png'),
('ai-ethics-course', 'ai', 'Etika & Batasan AI', 'AI Ethics & Limitations', 'Memahami batasan AI, mendeteksi bias data, dan menganalisis sistem rekomendasi media sosial.', 'Understand AI limitations, detect data bias, and analyze social media recommendation systems.', 'https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=600', 4, 'https://img.icons8.com/color/96/scale.png'),
('coding-basics', 'coding', 'Dasar Pemrograman', 'Coding Basics', 'Belajar pemrograman dasar dengan cara yang menyenangkan.', 'Learn programming concepts step-by-step.', 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600', 1, 'https://img.icons8.com/color/96/code.png'),
('data-science', 'data', 'Sains Data & ML', 'Data Science & ML', 'Eksplorasi bagaimana data melatih kecerdasan buatan.', 'Explore how data powers modern AI.', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600', 2, 'https://img.icons8.com/color/96/database.png'),
('image-classification-cnn', 'cnn', 'Klasifikasi Gambar (CNN)', 'Image Classification (CNN)', 'Bagaimana komputer melihat dan mengenali gambar di sekitarnya.', 'How machines see and recognize images.', 'https://images.unsplash.com/photo-1527474305487-b87b222841cc?w=600', 1, 'https://img.icons8.com/color/96/image.png')
`)

// 4.5. Seed Chapters
await client.query(`INSERT INTO chapters (slug, course_slug, level, title_id, title_en) VALUES
('ai-getting-started', 'intro-to-ai', 1, 'Pengenalan Dasar', 'Getting Started'),
('ai-around-us-chapter', 'intro-to-ai', 2, 'AI di Sekitar Kita', 'AI Around Us'),
('ai-types-of-learning', 'how-ai-learns-course', 1, 'Tipe Pembelajaran', 'Types of Learning'),
('ai-neural-networks', 'how-ai-learns-course', 2, 'Jaringan Saraf Tiruan', 'Neural Networks'),
('ai-generative-chapter', 'generative-ai-course', 1, 'Kecerdasan Buatan Generatif', 'Generative AI'),
('ai-limitations', 'ai-ethics-course', 1, 'Batasan AI', 'AI Limitations'),
('ai-recommendation', 'ai-ethics-course', 2, 'Sistem Rekomendasi', 'Recommendation Systems'),
('cnn-basics', 'image-classification-cnn', 1, 'Klasifikasi Gambar', 'Image Classification')
`)

// 5. Seed bilingual lessons

    await client.query(`INSERT INTO lessons (slug, course_slug, chapter_slug, lesson_order, language, title, summary, blocks) VALUES
      -- what-is-ai
      ('what-is-ai', 'intro-to-ai', 'ai-getting-started', 1, 'id', 'Apa itu AI?', 'Kenalan dengan kecerdasan buatan lewat contoh sehari-hari.',
        '[{"type":"text","markdown":"AI adalah komputer yang belajar dari contoh, bukan dihafalkan aturan. Kamu pasti sering lihat rekomendasi di YouTube atau TikTok — itu juga AI!"},{"type":"image","image_url":"https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600","caption":"Ilustrasi AI"},{"type":"quiz","question":"Bagaimana cara AI belajar?","choices":["Dengan diisi aturan satu per satu","Dengan melihat banyak contoh","Dengan sihir"],"answer_index":1,"hint":"Ingat analogi anak kecil belajar.","explanation":"AI belajar dari ribuan contoh, seperti anak kecil belajar mengenali kucing dari banyak gambar kucing.","reward_xp":20}]'::jsonb),
      ('what-is-ai', 'intro-to-ai', 'ai-getting-started', 1, 'en', 'What is AI?', 'Meet artificial intelligence through everyday examples.',
        '[{"type":"text","markdown":"AI is a computer that learns from examples instead of being told every rule. You''ve seen YouTube or TikTok recommendations — that''s AI too!"},{"type":"image","image_url":"https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600","caption":"AI illustration"},{"type":"quiz","question":"How does AI learn?","choices":["By having rules programmed one by one","By looking at many examples","By magic"],"answer_index":1,"hint":"Think of the toddler analogy.","explanation":"AI learns from thousands of examples, just like a toddler learns to recognize cats from many cat pictures.","reward_xp":20}]'::jsonb),

      -- ai-taxonomy
      ('ai-taxonomy', 'intro-to-ai', 'ai-getting-started', 2, 'id', 'Peta Keluarga AI: Taksonomi AI', 'Belajar bagaimana AI, Machine Learning, Deep Learning, dan Generative AI saling terhubung seperti lingkaran konsentris.',
        '[{"type":"text","markdown":"Pernahkah kamu mendengar istilah *Machine Learning* atau *Generative AI*? Istilah-istilah ini sering membuat bingung, padahal mereka sebenarnya adalah satu keluarga besar!\\\\n\\\\nBayangkan taksonomi AI seperti **kotak bekal susun** atau **lingkaran konsentris** (lingkaran di dalam lingkaran). Teknologi yang lebih spesifik berada di dalam lingkaran yang lebih besar."},{"type":"callout","style":"fun_fact","markdown":"**Analogi Anggota Keluarga AI:**\\\\n*   **AI (Kakek/Nenek):** Payung besar untuk semua teknologi cerdas.\\\\n*   **Machine Learning (Orang Tua):** Belajar dari contoh data.\\\\n*   **Deep Learning (Anak):** Meniru sel saraf otak manusia.\\\\n*   **Generative AI (Cucu):** Anak pintar yang bisa menggambar dan menulis cerita sendiri!"},{"type":"widget","widget_type":"taxonomy_concentric_circles","config":{"levels":[{"id":"ai","name":"Artificial Intelligence","short_desc":"Teknologi peniruan kecerdasan manusia","color":"#B19BB0"},{"id":"ml","name":"Machine Learning","short_desc":"Belajar pola dari data tanpa aturan manual","color":"#936B90"},{"id":"dl","name":"Deep Learning","short_desc":"Jaringan Saraf Tiruan dengan banyak lapisan","color":"#753F72"},{"id":"genai","name":"Generative AI","short_desc":"Menciptakan konten baru (gambar, teks, dll)","color":"#4A154B"}]},"reward_xp":50},{"type":"quiz","question":"Manakah teknologi yang merupakan bagian terdalam (paling spesifik) dari keluarga besar AI?","choices":["Artificial Intelligence (AI)","Machine Learning (ML)","Generative AI (GenAI)"],"answer_index":2,"hint":"Ingat bagian keluarga yang berada di lingkaran paling kecil di tengah.","explanation":"Generative AI adalah bagian terdalam yang memanfaatkan Deep Learning dan Machine Learning untuk menciptakan karya baru.","reward_xp":20}]'::jsonb),
      ('ai-taxonomy', 'intro-to-ai', 'ai-getting-started', 2, 'en', 'The AI Family Map: AI Taxonomy', 'Learn how AI, Machine Learning, Deep Learning, and Generative AI are nested together like concentric circles.',
        '[{"type":"text","markdown":"Have you ever heard the term *Machine Learning* or *Generative AI*? These terms can be confusing, but they actually belong to one big family!\\\\n\\\\nImagine the AI family tree like **nested lunchboxes** or **concentric circles** (circles inside circles). More specific technologies are placed inside larger ones."},{"type":"callout","style":"fun_fact","markdown":"**AI Family Analogy:**\\\\n*   **AI (Grandparent):** The large umbrella for all smart technologies.\\\\n*   **Machine Learning (Parent):** Learning from data examples.\\\\n*   **Deep Learning (Child):** Mimicking human brain nerve cells.\\\\n*   **Generative AI (Grandchild):** The smart kid who can draw and write stories independently!"},{"type":"widget","widget_type":"taxonomy_concentric_circles","config":{"levels":[{"id":"ai","name":"Artificial Intelligence","short_desc":"Technology mimicking human intelligence","color":"#B19BB0"},{"id":"ml","name":"Machine Learning","short_desc":"Learning patterns from data without manual rules","color":"#936B90"},{"id":"dl","name":"Deep Learning","short_desc":"Neural Networks with multiple hidden layers","color":"#753F72"},{"id":"genai","name":"Generative AI","short_desc":"Creating new content (images, text, etc.)","color":"#4A154B"}]},"reward_xp":50},{"type":"quiz","question":"Which technology is the deepest (most specific) part of the AI family tree?","choices":["Artificial Intelligence (AI)","Machine Learning (ML)","Generative AI (GenAI)"],"answer_index":2,"hint":"Think of the family member in the smallest circle at the center.","explanation":"Generative AI is the innermost branch that utilizes Deep Learning and Machine Learning to produce new creative works.","reward_xp":20}]'::jsonb),

      -- ai-vs-traditional-program
      ('ai-vs-traditional-program', 'intro-to-ai', 'ai-getting-started', 3, 'id', 'AI vs Program Biasa: Apa Bedanya?', 'Belajar perbedaan membuat program dengan if-else manual vs membiarkan komputer belajar dari data.',
        '[{"type":"text","markdown":"Pernahkah kamu membuat aturan game? Misalnya: ''Jika menekan tombol kanan, karakter bergerak ke kanan''. Itu adalah **pemrograman biasa (traditional programming)**, di mana manusia menuliskan aturan ''if-else'' satu per satu.\\n\\nSedangkan pada **Machine Learning (AI)**, kita tidak menuliskan aturan manual tersebut. Kita memberikan ribuan contoh permainan dan membiarkan komputer belajar sendiri cara memenangkan game tersebut!"},{"type":"callout","style":"fun_fact","markdown":"**Analogi Belajar Sepeda:**\\n*   **Program Biasa:** Buku petunjuk teoretis kaku berisi 100 aturan cara menyeimbangkan badan.\\n*   **AI (Machine Learning):** Mencoba naik sepeda langsung, jatuh berkali-kali (trial & error), lalu otot mengingat pola keseimbangan sendiri."},{"type":"widget","widget_type":"rule_vs_learning","config":{"scenario":"Labirin Kelinci","maze_size":"4x4","rules":["if obstacle in front -> turn left","if clear -> move forward"]},"reward_xp":50},{"type":"quiz","question":"Bagaimana Machine Learning berbeda dari pemrograman biasa?","choices":["Machine Learning belajar dari contoh data tanpa ditulis aturan manual satu per satu","Machine Learning membutuhkan manusia untuk menulis if-else setiap saat","Machine Learning tidak menggunakan komputer sekali"],"answer_index":0,"hint":"Ingat perbedaan menulis aturan manual vs belajar dari data latih.","explanation":"Pemrograman biasa mengharuskan manusia mengetik setiap aturan logika. Machine Learning memproses data latih untuk mengenali polanya sendiri.","reward_xp":20}]'::jsonb),
      ('ai-vs-traditional-program', 'intro-to-ai', 'ai-getting-started', 3, 'en', 'AI vs Traditional Program: What''s the Difference?', 'Learn the difference between coding manual rules with if-else vs letting computers learn from data.',
        '[{"type":"text","markdown":"Have you ever coded a game rule? For example: ''If the right button is pressed, the character moves right''. This is **traditional programming**, where humans write manual ''if-else'' rules one by one.\\n\\nBut with **Machine Learning (AI)**, we don''t write manual rules. We give the computer thousands of game examples and let it learn how to win by itself!"},{"type":"callout","style":"fun_fact","markdown":"**The Bicycle Analogy:**\\n*   **Traditional Program:** A rigid manual book with 100 rules on how to balance your body.\\n*   **AI (Machine Learning):** Actually riding the bike, falling down multiple times (trial & error), and letting your muscles remember the balance pattern."},{"type":"widget","widget_type":"rule_vs_learning","config":{"scenario":"Rabbit Maze","maze_size":"4x4","rules":["if obstacle in front -> turn left","if clear -> move forward"]},"reward_xp":50},{"type":"quiz","question":"How does Machine Learning differ from traditional programming?","choices":["Machine Learning learns from examples without manual rules programmed one by one","Machine Learning requires humans to write if-else rules all the time","Machine Learning does not use computers at all"],"answer_index":0,"hint":"Think about writing rules manually vs learning from training data.","explanation":"Traditional programming requires humans to write every logical rule. Machine Learning processes training data to identify patterns automatically.","reward_xp":20}]'::jsonb),

      -- ai-around-us
      ('ai-around-us', 'intro-to-ai', 'ai-around-us-chapter', 1, 'id', 'AI di Sekitar Kita', 'AI ada di mana-mana dalam kehidupan sehari-hari.',
        '[{"type":"text","markdown":"AI ada di mana-mana! Dari rekomendasi YouTube, filter wajah di TikTok, Google Maps, sampai mobil pintar.\\n\\nSetiap kali kamu scroll TikTok dan lihat video yang cocok dengan minatmu — itu AI yang bekerja!"},{"type":"image","image_url":"https://images.unsplash.com/photo-1531746790095-e0eb5a766087?w=600","caption":"AI di kehidupan sehari-hari"},{"type":"quiz","question":"Mana yang menggunakan AI?","choices":["Rekomendasi YouTube","Sendok","Batu"],"answer_index":0,"hint":"Coba pikirkan teknologi di sekitarmu.","explanation":"Rekomendasi YouTube menggunakan AI untuk menebak video yang kamu suka berdasarkan tontonan sebelumnya.","reward_xp":20}]'::jsonb),
      ('ai-around-us', 'intro-to-ai', 'ai-around-us-chapter', 1, 'en', 'AI Around Us', 'AI is everywhere in our daily lives.',
        '[{"type":"text","markdown":"AI is everywhere! From YouTube recommendations, face filters on social media, Google Maps, to smart cars.\\n\\nEvery time you scroll TikTok and see videos you like — that''s AI at work!"},{"type":"image","image_url":"https://images.unsplash.com/photo-1531746790095-e0eb5a766087?w=600","caption":"AI in everyday life"},{"type":"quiz","question":"Which one uses AI?","choices":["YouTube recommendations","A spoon","A rock"],"answer_index":0,"hint":"Think about the technology around you.","explanation":"YouTube recommendations use AI to guess videos you''ll like based on what you''ve watched before.","reward_xp":20}]'::jsonb),

      -- ai-sensors-perception
      ('ai-sensors-perception', 'intro-to-ai', 'ai-around-us-chapter', 2, 'id', 'Panca Indra AI: Bagaimana AI Melihat & Mendengar?', 'Kenalan dengan sensor kamera dan mikrofon sebagai panca indra komputer untuk menangkap data.',
        '[{"type":"text","markdown":"Manusia menggunakan mata untuk melihat dan telinga untuk mendengar. Komputer menggunakan **sensor** sebagai panca indranya!\\n\\n*   **Kamera** bertindak sebagai ''mata'' AI untuk menangkap gambar (*Computer Vision*).\\n*   **Mikrofon** bertindak sebagai ''telinga'' AI untuk menangkap suara (*Speech Recognition*)."},{"type":"callout","style":"fun_fact","markdown":"Kamera digital menangkap ribuan titik cahaya kecil (piksel), sedangkan mikrofon merekam getaran gelombang suara di udara dan mengubahnya menjadi deretan angka."},{"type":"widget","widget_type":"sensory_sandbox","config":{"sensors":[{"type":"camera","label":"Mata AI (Kamera)","mode":"vision"},{"type":"microphone","label":"Telinga AI (Mikrofon)","mode":"audio"}]},"reward_xp":50},{"type":"quiz","question":"Sensor apa yang digunakan AI untuk mengenali wajah kita di smartphone?","choices":["Kamera","Mikrofon","Sensor Suhu"],"answer_index":0,"hint":"Mana yang bisa memotret atau menangkap gambar wajah?","explanation":"Kamera menangkap gambar wajah kita, lalu sistem Computer Vision pada AI mencocokkan wajah tersebut dengan database pemilik ponsel.","reward_xp":20}]'::jsonb),
      ('ai-sensors-perception', 'intro-to-ai', 'ai-around-us-chapter', 2, 'en', 'AI Sensors: How AI Sees & Hears?', 'Learn how cameras and microphones act as sensors for computers to perceive the world.',
        '[{"type":"text","markdown":"Humans use eyes to see and ears to hear. Computers use **sensors** as their senses!\\n\\n*   **Cameras** act as the AI''s ''eyes'' to capture images (*Computer Vision*).\\n*   **Microphones** act as the AI''s ''ears'' to capture voice (*Speech Recognition*)."},{"type":"callout","style":"fun_fact","markdown":"A digital camera captures thousands of tiny light points (pixels), while a microphone records sound wave vibrations in the air and converts them into numbers."},{"type":"widget","widget_type":"sensory_sandbox","config":{"sensors":[{"type":"camera","label":"AI Eyes (Camera)","mode":"vision"},{"type":"microphone","label":"AI Ears (Microphone)","mode":"audio"}]},"reward_xp":50},{"type":"quiz","question":"Which sensor does AI use to recognize our face on a smartphone?","choices":["Camera","Microphone","Temperature Sensor"],"answer_index":0,"hint":"Which sensor captures or takes pictures of faces?","explanation":"The camera captures our face image, and then the Computer Vision system matches the face with the phone owner''s database.","reward_xp":20}]'::jsonb),

      -- how-ai-learns
      ('how-ai-learns', 'how-ai-learns-course', 'ai-types-of-learning', 1, 'id', 'Bagaimana AI Belajar?', 'AI belajar dari ribuan contoh yang disebut data latih.',
        '[{"type":"text","markdown":"AI belajar dari ribuan contoh yang disebut **data latih** (training data). Semakin banyak dan bervariasi contohnya, semakin pintar AI-nya!\\n\\nMisalnya, untuk mengenali kucing, AI perlu melihat ribuan gambar kucing — kucing orange, kucing hitam, kucing tidur, kucing lari."},{"type":"callout","style":"fun_fact","markdown":"Tahukah kamu? ChatGPT dilatih dengan miliaran kata dari buku, artikel, dan internet!"},{"type":"widget","widget_type":"train_your_own_ai","config":{"min_dataset_size": 10, "max_dataset_size": 1000, "min_epochs": 5, "max_epochs": 100},"reward_xp":50},{"type":"quiz","question":"Apa yang dibutuhkan AI untuk belajar?","choices":["Data latih","Cemilan","Listrik"],"answer_index":0,"hint":"Ingat bagian AI belajar dari contoh.","explanation":"AI butuh data latih — contoh-contoh yang bisa dipelajari untuk mengenali pola.","reward_xp":20}]'::jsonb),
      ('how-ai-learns', 'how-ai-learns-course', 'ai-types-of-learning', 1, 'en', 'How AI Learns', 'AI learns from thousands of examples called training data.',
        '[{"type":"text","markdown":"AI learns from thousands of examples called **training data**. The more varied the examples, the smarter the AI gets!\\n\\nFor example, to recognize cats, AI needs to see thousands of cat pictures — orange cats, black cats, sleeping cats, running cats."},{"type":"callout","style":"fun_fact","markdown":"Did you know? ChatGPT was trained on billions of words from books, articles, and the internet!"},{"type":"widget","widget_type":"train_your_own_ai","config":{"min_dataset_size": 10, "max_dataset_size": 1000, "min_epochs": 5, "max_epochs": 100},"reward_xp":50},{"type":"quiz","question":"What does AI need to learn?","choices":["Training data","Snacks","Electricity"],"answer_index":0,"hint":"Think about how AI learns from examples.","explanation":"AI needs training data — examples it can study to recognize patterns.","reward_xp":20}]'::jsonb),

      -- ai-data-types
      ('ai-data-types', 'how-ai-learns-course', 'ai-types-of-learning', 2, 'id', 'Mengenal Data & Tipe Data', 'Eksplorasi apa itu data dan bagaimana cara membedakan data kuantitatif vs kategorikal.',
        '[{"type":"text","markdown":"AI membutuhkan **data** untuk belajar. Tapi, apakah kamu tahu apa itu data?\\\\n\\\\n*   **Data:** Fakta mentah tunggal (misal: suhu kulkas 2.5°C).\\\\n*   **Dataset:** Kumpulan data terstruktur (misal: tabel daftar belanjaan).\\\\n*   **Basis Data (Database):** Lemari penyimpanan besar tempat semua dataset disimpan agar mudah diakses komputer."},{"type":"callout","style":"fun_fact","markdown":"**Tipe Data Terstruktur di Toko Kelontong Pintar 🏪**\\\\n\\\\n1.  **Kuantitatif (Angka):**\\\\n    *   **Kontinu (Desimal):** Nilai yang diukur (misal: Suhu kulkas **2.5°C** atau Berat buah **1.2 kg**).\\\\n    *   **Diskrit (Bulat):** Nilai yang dihitung secara utuh (misal: **12 kaleng** soda, tidak bisa 12.5 kaleng).\\\\n2.  **Kategorikal (Label/Kategori):**\\\\n    *   **Nominal (Nama):** Label pembeda tanpa peringkat (misal: jenis buah **Apel, Jeruk, Mangga**).\\\\n    *   **Ordinal (Peringkat):** Label yang memiliki tingkat urutan (misal: rating kepuasan pelanggan dari **Bintang 1 sampai Bintang 5**)."},{"type":"widget","widget_type":"grocery_sorter","config":{"items":[{"id":1,"name":"Suhu Kulkas Toko (2.5°C)","type":"kontinu","emoji":"🌡️","hint":"Bisa bernilai desimal/koma dan diukur secara kontinu."},{"id":2,"name":"Jumlah Kaleng Soda (12 Kaleng)","type":"diskrit","emoji":"🥤","hint":"Merupakan bilangan bulat utuh dan tidak bisa dibagi koma."},{"id":3,"name":"Jenis Buah (Apel, Jeruk, Mangga)","type":"nominal","emoji":"🍎","hint":"Label/nama kategori saja tanpa ada peringkat."},{"id":4,"name":"Rating Puas Pelanggan (Bintang 1-5)","type":"ordinal","emoji":"⭐","hint":"Kategori yang memiliki tingkat urutan atau peringkat."}]},"reward_xp":50},{"type":"quiz","question":"Jika kamu menghitung jumlah siswa di dalam kelas, data tersebut termasuk ke dalam tipe data apa?","choices":["Data Kontinu (Desimal)","Data Diskrit (Bilangan Bulat)","Data Nominal (Label)"],"answer_index":1,"hint":"Ingat apakah jumlah manusia bisa dihitung dalam pecahan desimal?","explanation":"Jumlah siswa selalu dihitung menggunakan bilangan bulat utuh (tidak ada setengah orang), sehingga termasuk data diskrit.","reward_xp":20}]'::jsonb),
      ('ai-data-types', 'how-ai-learns-course', 'ai-types-of-learning', 2, 'en', 'Introduction to Data & Data Types', 'Explore what data is and how to distinguish quantitative vs categorical data.',
        '[{"type":"text","markdown":"AI requires **data** to learn. But do you know what data actually is?\\\\n\\\\n*   **Data:** A single raw fact (e.g., refrigerator temperature 2.5°C).\\\\n*   **Dataset:** A structured collection of data (e.g., a grocery shopping table).\\\\n*   **Database:** A large storage cabinet where all datasets are stored for easy computer access."},{"type":"callout","style":"fun_fact","markdown":"**Structured Data Types in a Smart Grocery Store 🏪**\\\\n\\\\n1.  **Quantitative (Numbers):**\\\\n    *   **Continuous (Decimal):** Values that are measured (e.g., fridge temperature **2.5°C** or fruit weight **1.2 kg**).\\\\n    *   **Discrete (Integer):** Values that are counted in wholes (e.g., **12 cans** of soda, not 12.5 cans).\\\\n2.  **Categorical (Labels/Categories):**\\\\n    *   **Nominal (Name):** Distinguishing labels without ranking (e.g., fruit types **Apple, Orange, Mango**).\\\\n    *   **Ordinal (Rank):** Labels that have a specific order (e.g., customer satisfaction rating from **1 Star to 5 Stars**)."},{"type":"widget","widget_type":"grocery_sorter","config":{"items":[{"id":1,"name":"Shop Fridge Temperature (2.5°C)","type":"kontinu","emoji":"🌡️","hint":"Can be decimal/fractional and is measured continuously."},{"id":2,"name":"Number of Soda Cans (12 Cans)","type":"diskrit","emoji":"🥤","hint":"Is a whole integer and cannot be split into decimals."},{"id":3,"name":"Fruit Type (Apple, Orange, Mango)","type":"nominal","emoji":"🍎","hint":"Only a category label with no specific ranking."},{"id":4,"name":"Customer Satisfaction Rating (1-5 Stars)","type":"ordinal","emoji":"⭐","hint":"A category that has a natural order or ranking."}]},"reward_xp":50},{"type":"quiz","question":"If you count the number of students in a classroom, what type of data is that?","choices":["Continuous Data (Decimal)","Discrete Data (Whole Number)","Nominal Data (Label)"],"answer_index":1,"hint":"Can the number of humans be counted in decimal fractions?","explanation":"The number of students is always counted in whole numbers (there is no half person), which makes it discrete data.","reward_xp":20}]'::jsonb),

      -- ai-data-gigo
      ('ai-data-gigo', 'how-ai-learns-course', 'ai-types-of-learning', 3, 'id', 'Sampah Masuk, Sampah Keluar (GIGO)', 'Belajar mengapa kualitas data latih sangat menentukan kecerdasan AI.',
        '[{"type":"text","markdown":"Di dunia komputer, ada pepatah populer:\\\\n**''''Garbage In, Garbage Out'''' (GIGO)** yang berarti **Sampah Masuk, Sampah Keluar**.\\\\n\\\\nJika kita memberikan makanan berupa data latih yang buruk, rusak, atau keliru (sampah) kepada AI, maka kecerdasan AI yang dihasilkan pun akan buruk (sampah)!"},{"type":"callout","style":"fun_fact","markdown":"**Masalah Umum pada Data Kotor 🕵️‍♂️**\\\\n*   **Missing Value (Data Kosong):** Informasi penting yang hilang (misal: kolom harga kosong).\\\\n*   **Outlier (Pencilan Ekstrim):** Nilai aneh yang tidak wajar akibat sensor rusak (misal: suhu ruangan tertulis 100°C).\\\\n*   **Data Duplikat:** Informasi yang sama persis tercatat berkali-kali sehingga membuat AI bingung."},{"type":"widget","widget_type":"data_cleaner","config":{"rows":[{"id":1,"product":"Apel","price":"Rp 5.000","status":"clean"},{"id":2,"product":"Apel","price":"Rp 5.000","status":"duplicate","issue":"Data ini sama persis dengan baris 1!"},{"id":3,"product":"Jeruk","price":"","status":"missing_value","issue":"Harganya kosong/tidak terisi!"},{"id":4,"product":"Susu Kotak","price":"Rp 150.000.000","status":"outlier","issue":"Harganya terlalu mahal/tidak wajar!"}]},"reward_xp":50},{"type":"quiz","question":"Apa yang terjadi jika kita melatih model AI pendeteksi wajah hanya menggunakan foto-foto yang buram dan gelap?","choices":["AI akan tetap pintar mendeteksi wajah dengan jelas","AI akan kesulitan mengenali wajah karena kualitas data latih buruk","AI akan otomatis menerangkan foto secara ajaib"],"answer_index":1,"hint":"Ingat prinsip Garbage In, Garbage Out.","explanation":"Ini adalah contoh prinsip GIGO. Karena data inputnya buram dan gelap (garbage), hasil prediksi AI pun akan buruk (garbage).","reward_xp":20}]'::jsonb),
      ('ai-data-gigo', 'how-ai-learns-course', 'ai-types-of-learning', 3, 'en', 'Garbage In, Garbage Out (GIGO)', 'Learn why training data quality determines how smart an AI gets.',
        '[{"type":"text","markdown":"In the computer world, there is a popular saying:\\\\n**''''Garbage In, Garbage Out'''' (GIGO)**.\\\\n\\\\nIf we feed bad, corrupted, or incorrect training data (garbage) to an AI, the resulting AI intelligence will also be bad (garbage)!"},{"type":"callout","style":"fun_fact","markdown":"**Common Issues in Dirty Data 🕵️‍♂️**\\\\n*   **Missing Value:** Crucial information that is lost or blank (e.g., empty price column).\\\\n*   **Outlier:** Strange and unrealistic values due to sensor malfunction (e.g., room temperature recorded as 100°C).\\\\n*   **Duplicate Data:** The exact same information recorded multiple times, causing AI to be biased."},{"type":"widget","widget_type":"data_cleaner","config":{"rows":[{"id":1,"product":"Apple","price":"Rp 5.000","status":"clean"},{"id":2,"product":"Apple","price":"Rp 5.000","status":"duplicate","issue":"This data is identical to row 1!"},{"id":3,"product":"Orange","price":"","status":"missing_value","issue":"The price is empty!"},{"id":4,"product":"Milk Box","price":"Rp 150.000.000","status":"outlier","issue":"The price is way too high and unrealistic!"}]},"reward_xp":50},{"type":"quiz","question":"What happens if we train a facial recognition AI model using only blurry and dark photos?","choices":["AI will still be smart enough to recognize faces clearly","AI will struggle to recognize faces due to poor training data quality","AI will automatically brighten the photos magically"],"answer_index":1,"hint":"Remember the Garbage In, Garbage Out principle.","explanation":"This is a classic GIGO case. Since the input training data is blurry and dark (garbage), the AI''s predictions will also be poor (garbage).","reward_xp":20}]'::jsonb),
      -- supervised-vs-unsupervised
      ('supervised-vs-unsupervised', 'how-ai-learns-course', 'ai-types-of-learning', 4, 'id', 'Supervised vs Unsupervised', 'Dua cara AI belajar: dengan guru (supervised) atau sendiri (unsupervised).',
        '[{"type":"text","markdown":"**Supervised learning** seperti belajar dengan guru — kamu dikasih tahu jawabannya dulu, baru belajar polanya.\\n\\n**Unsupervised learning** seperti mencoba mengelompokkan mainan sendiri tanpa diberi tahu nama kelompoknya."},{"type":"image","image_url":"https://images.unsplash.com/photo-1509228627152-72e2aac4cb60?w=600","caption":"Supervised vs Unsupervised"},{"type":"widget","widget_type":"sorting_game","config":{"mode":"both"},"reward_xp":50},{"type":"quiz","question":"Supervised learning menggunakan...","choices":["Data berlabel","Data tanpa label","Data acak"],"answer_index":0,"hint":"Apa bedanya belajar dengan guru vs sendirian?","explanation":"Supervised learning menggunakan data yang sudah diberi label — seperti PR yang sudah dikoreksi guru.","reward_xp":20}]'::jsonb),
      ('supervised-vs-unsupervised', 'how-ai-learns-course', 'ai-types-of-learning', 4, 'en', 'Supervised vs Unsupervised', 'Two ways AI learns: with a teacher (supervised) or by itself (unsupervised).',
        '[{"type":"text","markdown":"**Supervised learning** is like learning with a teacher — you''re shown the answers first, then learn the patterns.\\n\\n**Unsupervised learning** is like sorting toys into groups without being told what the groups are called."},{"type":"image","image_url":"https://images.unsplash.com/photo-1509228627152-72e2aac4cb60?w=600","caption":"Supervised vs Unsupervised"},{"type":"widget","widget_type":"sorting_game","config":{"mode":"both"},"reward_xp":50},{"type":"quiz","question":"Supervised learning uses...","choices":["Labeled data","Unlabeled data","Random data"],"answer_index":0,"hint":"What''s the difference between learning with a teacher vs alone?","explanation":"Supervised learning uses labeled data — like homework that''s already been graded by a teacher.","reward_xp":20}]'::jsonb),

      -- reinforcement-learning-basics
      ('reinforcement-learning-basics', 'how-ai-learns-course', 'ai-types-of-learning', 5, 'id', 'Belajar dari Hadiah & Hukuman', 'Mengenal Reinforcement Learning, cara melatih AI menggunakan sistem reward (hadiah) dan penalty (hukuman).',
        '[{"type":"text","markdown":"Bagaimana cara melatih anjing peliharaan melakukan trik baru? Kita memberinya snack lezat (**hadiah/reward**) jika ia melompat dengan benar, dan tidak memberi snack (**hukuman/penalty**) jika ia salah.\\n\\nDi dalam AI, metode ini disebut **Reinforcement Learning**! AI mencoba berkali-kali secara acak, dan secara bertahap belajar memilih tindakan yang mengumpulkan skor hadiah terbanyak."},{"type":"callout","style":"fun_fact","markdown":"Banyak game AI (seperti AI catur AlphaGo atau AI game balapan) dilatih menggunakan metode ini. AI bermain jutaan kali melawan dirinya sendiri untuk mencari strategi terbaik!"},{"type":"widget","widget_type":"reward_trainer","config":{"environment":"Dog Jump","actions":["Jump Low","Jump Medium","Jump High"],"target_obstacle_height":2},"reward_xp":50},{"type":"quiz","question":"Metode belajar AI dengan mencoba sendiri dan mendapatkan skor hadiah/hukuman disebut...","choices":["Supervised Learning","Reinforcement Learning","Unsupervised Learning"],"answer_index":1,"hint":"Kata ''Reinforce'' berarti memperkuat tindakan dengan hadiah.","explanation":"Reinforcement Learning melatih AI (disebut agent) melalui interaksi berulang dengan lingkungan untuk memaksimalkan total hadiah.","reward_xp":20}]'::jsonb),
      ('reinforcement-learning-basics', 'how-ai-learns-course', 'ai-types-of-learning', 5, 'en', 'Learning from Rewards & Penalties', 'Introduction to Reinforcement Learning, training AI using rewards and penalties.',
        '[{"type":"text","markdown":"How do you train a pet dog to do a new trick? We give it a delicious treat (**reward**) if it jumps correctly, and no treat (**penalty**) if it fails.\\n\\nIn AI, this method is called **Reinforcement Learning**! The AI tries actions randomly at first, and gradually learns to choose the actions that collect the most reward points."},{"type":"callout","style":"fun_fact","markdown":"Many gaming AIs (like the AlphaGo chess AI or racing game AIs) are trained using this method. The AI plays millions of times against itself to discover the best strategy!"},{"type":"widget","widget_type":"reward_trainer","config":{"environment":"Dog Jump","actions":["Jump Low","Jump Medium","Jump High"],"target_obstacle_height":2},"reward_xp":50},{"type":"quiz","question":"What is the AI learning method that involves trial-and-error and rewards/penalties called?","choices":["Supervised Learning","Reinforcement Learning","Unsupervised Learning"],"answer_index":1,"hint":"The word ''Reinforce'' means strengthening behavior using rewards.","explanation":"Reinforcement Learning trains an AI (agent) through repeated interactions with an environment to maximize total rewards.","reward_xp":20}]'::jsonb),

      -- thinking-like-a-neuron
      ('thinking-like-a-neuron', 'how-ai-learns-course', 'ai-neural-networks', 1, 'id', 'Berpikir Seperti Neuron', 'Belajar bagaimana neuron buatan mengambil keputusan menggunakan bobot dan ambang batas.',
        '[{"type":"text","markdown":"Otak kita memiliki miliaran sel pintar bernama **neuron** yang bertugas mengambil keputusan. AI meniru cara kerja ini menggunakan **Neuron Buatan (Linear Threshold Unit)**.\\n\\nBagaimana neuron buatan ini berpikir? Mari kita gunakan analogi sederhana!"},{"type":"callout","style":"fun_fact","markdown":"**Analogi Memilih Camilan 🍦**\\n\\nBayangkan kamu ingin membeli es krim. Ada 2 pertimbangan (Input):\\n1. **Apakah rasanya manis?** (Sangat penting bagi kamu $\\\\rightarrow$ **Bobot tinggi = 3**)\\n2. **Apakah warnanya biru?** (Kurang penting bagi kamu $\\\\rightarrow$ **Bobot rendah = 1**)\\n\\nSetiap pertimbangan dikalikan tingkat kepentingannya (**Bobot**). Jika total kepuasannya melewati batas kemantapan hatimu (**Ambang Batas / Threshold = 3**), barulah kamu **memutuskan membeli es krim tersebut (Neuron Aktif = 1)**!"},{"type":"text","markdown":"Di dalam AI, neuron buatan melakukan hal yang persis sama:\\n*   **Input ($x$)**: Ciri-ciri objek yang dideteksi (misal: Merah, Bintik).\\n*   **Bobot ($w$)**: Seberapa penting ciri tersebut dalam mengambil keputusan.\\n*   **Threshold ($\\\\theta$)**: Batas keyakinan minimum agar neuron aktif (mengeluarkan output 1)."},{"type":"callout","style":"warning","markdown":"**Misi Kamu Sebagai AI Trainer 🤠**\\n\\nTugasmu adalah melatih sebuah neuron agar otomatis mengenali buah **Stroberi** (Output = 1) DAN menolak buah lain (Output = 0).\\n\\nStroberi memiliki ciri: **Merah (1)** DAN **Bintik (1)**. Buah lain seperti Pisang (0, 0), Apel (1, 0), dan Kiwi (0, 1) bukan stroberi.\\n\\n**Tujuan Praktik:** Sesuaikan Bobot dan Threshold pada slider di bawah agar neuron hanya menghasilkan **Output: 1** saat mendeteksi Stroberi. Pastikan semua buah di tabel evaluasi tercentang hijau!"},{"type":"widget","widget_type":"neuron_sandbox","config":{"target_class":"Stroberi","inputs":[{"name":"Merah","key":"red"},{"name":"Bintik","key":"spots"}],"truth_table":[{"inputs":{"red":0,"spots":0},"expected":0,"fruit":"Pisang"},{"inputs":{"red":1,"spots":0},"expected":0,"fruit":"Apel"},{"inputs":{"red":0,"spots":1},"expected":0,"fruit":"Kiwi"},{"inputs":{"red":1,"spots":1},"expected":1,"fruit":"Stroberi"}],"min_weight":-5,"max_weight":5,"min_threshold":0,"max_threshold":10},"reward_xp":50},{"type":"quiz","question":"Apa yang terjadi jika total nilai input dikali bobot lebih kecil dari ambang batas (threshold)?","choices":["Neuron tetap mati/tidak aktif","Neuron meledak","Neuron langsung aktif"],"answer_index":0,"hint":"Neuron hanya aktif jika nilai input melampaui ambang batas.","explanation":"Neuron buatan (LTU) hanya akan menembakkan sinyal (aktif) jika total nilai input x bobot sama dengan atau melebihi threshold.","reward_xp":20}]'::jsonb),
      ('thinking-like-a-neuron', 'how-ai-learns-course', 'ai-neural-networks', 1, 'en', 'Thinking Like a Neuron', 'Learn how artificial neurons make decisions using weights and thresholds.',
        '[{"type":"text","markdown":"Our brain has billions of smart cells called **neurons** that make decisions. AI mimics this using an **Artificial Neuron (Linear Threshold Unit)**.\\n\\nHow does this artificial neuron think? Let''s use a simple analogy!"},{"type":"callout","style":"fun_fact","markdown":"**The Snack Analogy 🍦**\\n\\nImagine you want to buy an ice cream. You have 2 factors (Inputs):\\n1. **Is it sweet?** (Very important to you $\\\\rightarrow$ **High Weight = 3**)\\n2. **Is it blue?** (Not very important $\\\\rightarrow$ **Low Weight = 1**)\\n\\nEach factor is multiplied by its importance (**Weight**). If the total satisfaction meets or exceeds your decision barrier (**Threshold = 3**), you **decide to buy the ice cream (Neuron Activates = 1)**!"},{"type":"text","markdown":"In AI, an artificial neuron does the exact same thing:\\n*   **Input ($x$)**: Object features (e.g., Red, Spots).\\n*   **Weight ($w$)**: How important that feature is in making decisions.\\n*   **Threshold ($\\\\theta$)**: The minimum confidence needed for the neuron to activate (output 1)."},{"type":"callout","style":"warning","markdown":"**Your Mission as an AI Trainer 🤠**\\n\\nYour task is to train a neuron to automatically recognize **Strawberry** (Output = 1) and reject other fruits (Output = 0).\\n\\nStrawberry has features: **Red (1)** AND **Spots (1)**. Other fruits like Banana (0, 0), Apple (1, 0), and Kiwi (0, 1) are not strawberries.\\n\\n**Practice Goal:** Adjust the Weights and Threshold sliders below so the neuron only outputs **Output: 1** for Strawberry. Make sure all fruits in the evaluation table get green checkmarks!"},{"type":"widget","widget_type":"neuron_sandbox","config":{"target_class":"Strawberry","inputs":[{"name":"Red","key":"red"},{"name":"Spots","key":"spots"}],"truth_table":[{"inputs":{"red":0,"spots":0},"expected":0,"fruit":"Banana"},{"inputs":{"red":1,"spots":0},"expected":0,"fruit":"Apple"},{"inputs":{"red":0,"spots":1},"expected":0,"fruit":"Kiwi"},{"inputs":{"red":1,"spots":1},"expected":1,"fruit":"Strawberry"}],"min_weight":-5,"max_weight":5,"min_threshold":0,"max_threshold":10},"reward_xp":50},{"type":"quiz","question":"What happens if the total input times weights is less than the threshold?","choices":["The neuron remains inactive","The neuron explodes","The neuron instantly activates"],"answer_index":0,"hint":"Neurons only fire when the input sum meets or exceeds the threshold.","explanation":"An artificial neuron (LTU) only fires a signal (activates) if the weighted sum of inputs meets or exceeds the threshold.","reward_xp":20}]'::jsonb),

      -- how-ai-makes-sentences
      ('how-ai-makes-sentences', 'generative-ai-course', 'ai-generative-chapter', 1, 'id', 'Bagaimana AI Membuat Kalimat?', 'Belajar bagaimana Generative AI merangkai kalimat kata demi kata menggunakan probabilitas.',
        '[{"type":"text","markdown":"Kamu mungkin pernah menggunakan ChatGPT untuk membuat cerita atau menjawab pertanyaan. Tapi, tahukah kamu bagaimana AI bisa merangkai kata-kata tersebut?\\n\\nAI generatif tidak benar-benar memahami makna kalimat seperti manusia. AI bekerja seperti **mesin penebak kata** pintar yang memilih kata berikutnya berdasarkan **probabilitas matematika** (kemungkinan tertinggi)!"},{"type":"callout","style":"fun_fact","markdown":"**Analogi Penebak Kata:**\\nJika kamu mengetik kalimat: **''Kucing tidur di atas...''**, kata berikutnya yang paling mungkin menurut statistik adalah **''kasur''** atau **''keset''**, bukan **''sepeda''**! AI menghitung kemungkinan ini."},{"type":"widget","widget_type":"next_word_predictor","config":{"story":"Kucing tidur di atas...","steps":[{"current_text":"Kucing tidur di atas","options":[{"word":"kasur","probability":75,"is_correct":true},{"word":"sepeda","probability":5,"is_correct":false},{"word":"awan","probability":10,"is_correct":false},{"word":"meja","probability":10,"is_correct":true}]},{"current_text":"Kucing tidur di atas kasur","options":[{"word":"yang","probability":85,"is_correct":true},{"word":"karena","probability":5,"is_correct":false},{"word":"dengan","probability":10,"is_correct":false}]},{"current_text":"Kucing tidur di atas kasur yang","options":[{"word":"empuk","probability":90,"is_correct":true},{"word":"sepatu","probability":2,"is_correct":false},{"word":"berteriak","probability":8,"is_correct":false}]}]},"reward_xp":50},{"type":"quiz","question":"Bagaimana Generative AI memilih kata berikutnya saat membuat teks?","choices":["Menebak secara acak","Memilih kata berdasarkan probabilitas tertinggi","Membaca pikiran pengguna"],"answer_index":1,"hint":"AI bekerja seperti mesin statistik penebak kata berikutnya.","explanation":"Generative AI menggunakan statistik untuk menebak kata berikutnya yang paling cocok mengalir setelah kata sebelumnya.","reward_xp":20}]'::jsonb),
      ('how-ai-makes-sentences', 'generative-ai-course', 'ai-generative-chapter', 1, 'en', 'How AI Makes Sentences?', 'Learn how Generative AI strings words together word-by-word using probabilities.',
        '[{"type":"text","markdown":"You might have used ChatGPT to write a story or answer a question. But do you know how it generates those words?\\n\\nGenerative AI does not understand the meaning of sentences like humans do. Instead, it works like a smart **word guessing machine** that selects the next word based on **mathematical probability**!"},{"type":"callout","style":"fun_fact","markdown":"**Word Guessing Analogy:**\\nIf you type: **''The cat sleeps on the...''**, the statistically most likely next word is **''bed''** or **''rug''**, not **''bicycle''**! AI calculates these probabilities."},{"type":"widget","widget_type":"next_word_predictor","config":{"story":"The cat sleeps on the...","steps":[{"current_text":"The cat sleeps on the","options":[{"word":"bed","probability":75,"is_correct":true},{"word":"bicycle","probability":5,"is_correct":false},{"word":"cloud","probability":10,"is_correct":false},{"word":"table","probability":10,"is_correct":true}]},{"current_text":"The cat sleeps on the bed","options":[{"word":"which","probability":85,"is_correct":true},{"word":"because","probability":5,"is_correct":false},{"word":"with","probability":10,"is_correct":false}]},{"current_text":"The cat sleeps on the bed which","options":[{"word":"is soft","probability":90,"is_correct":true},{"word":"screams","probability":2,"is_correct":false},{"word":"runs","probability":8,"is_correct":false}]}]},"reward_xp":50},{"type":"quiz","question":"How does Generative AI select the next word when writing text?","choices":["By guessing completely randomly","By choosing the word with the highest probability","By reading the user''s mind"],"answer_index":1,"hint":"AI acts like a statistical word predictor.","explanation":"Generative AI uses statistics to predict the next word that most naturally flows after the previous words.","reward_xp":20}]'::jsonb),

      -- how-ai-draws
      ('how-ai-draws', 'generative-ai-course', 'ai-generative-chapter', 2, 'id', 'Bagaimana AI Menggambar?', 'Memahami cara kerja AI pembuat gambar lewat proses membersihkan coretan (diffusion).',
        '[{"type":"text","markdown":"AI Generatif tidak hanya bisa menulis cerita, tapi juga menggambar lukisan indah! Bagaimana caranya?\\n\\nAI pembuat gambar menggunakan proses bernama **Diffusion**. AI mulai dari gambar penuh coretan acak yang rusak (**noise**), lalu perlahan-lahan membersihkan coretan tersebut langkah demi langkah sampai terbentuk gambar yang kita minta!"},{"type":"callout","style":"fun_fact","markdown":"**Analogi Mengukir:**\\nBayangkan seorang pemahat patung yang mulai dari balok batu kasar (seperti *noise* acak). Dia memahat dan membuang bagian batu yang tidak penting sedikit demi sedikit hingga patung kuda yang indah muncul."},{"type":"widget","widget_type":"diffusion_sandbox","config":{"prompts":[{"text":"Astronaut cat on the moon","image_steps":["https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&q=10","https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&q=50","https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600"]},{"text":"Robot playing soccer","image_steps":["https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=100&q=10","https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=300&q=50","https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600"]}]},"reward_xp":50},{"type":"quiz","question":"Teknik AI generatif menggambar gambar baru dengan cara membersihkan coretan acak secara bertahap disebut...","choices":["Diffusion","Supervision","Tokenization"],"answer_index":0,"hint":"Sama seperti proses menyebarkan lalu membersihkan debu/noise.","explanation":"Model Diffusion dilatih untuk merekonstruksi gambar dengan menghilangkan noise (gangguan acak) secara iteratif berdasarkan prompt teks.","reward_xp":20}]'::jsonb),
      ('how-ai-draws', 'generative-ai-course', 'ai-generative-chapter', 2, 'en', 'How AI Draws?', 'Understand how image-generating AIs work by cleaning up random noise (diffusion process).',
        '[{"type":"text","markdown":"Generative AI can write stories, but it can also draw beautiful pictures! How does it do it?\\n\\nImage-generating AIs use a process called **Diffusion**. The AI starts with an image full of random static/pixels (**noise**), and slowly cleans up that noise step-by-step until the requested picture appears!"},{"type":"callout","style":"fun_fact","markdown":"**The Sculpting Analogy:**\\nImagine a sculptor starting with a rough block of stone (like random *noise*). He chisels away the unneeded stone piece-by-piece until a beautiful horse statue emerges."},{"type":"widget","widget_type":"diffusion_sandbox","config":{"prompts":[{"text":"Astronaut cat on the moon","image_steps":["https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&q=10","https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&q=50","https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600"]},{"text":"Robot playing soccer","image_steps":["https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=100&q=10","https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=300&q=50","https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600"]}]},"reward_xp":50},{"type":"quiz","question":"What is the Generative AI technique that draws new images by gradually cleaning up random noise called?","choices":["Diffusion","Supervision","Tokenization"],"answer_index":0,"hint":"Like spreading and then cleaning up random dust/noise.","explanation":"Diffusion models are trained to reconstruct images by iteratively removing noise based on the input text prompt.","reward_xp":20}]'::jsonb),

      -- ai-can-be-wrong
      ('ai-can-be-wrong', 'ai-ethics-course', 'ai-limitations', 1, 'id', 'AI Bisa Salah', 'AI tidak selalu benar — bahkan saat sangat yakin sekalipun.',
        '[{"type":"text","markdown":"AI tidak selalu benar! Kadang AI sangat yakin tapi tetap salah. Itulah kenapa kita harus selalu berpikir kritis saat menggunakan AI.\\n\\nMisalnya, AI mungkin mengira pizza sebagai koin karena sama-sama bulat dan kuning — dengan keyakinan 99%!"},{"type":"callout","style":"warning","markdown":"AI yang yakin 99% pun bisa salah. Contoh: AI bisa mengira pizza sebagai koin karena sama-sama bulat dan kuning!"},{"type":"widget","widget_type":"prompt_evaluator","config":{"scenario":"Menanyakan AI tentang buah apel","prompt_options":["Jelaskan apa itu buah apel dan kandungannya.","Tulis puisi pendek tentang buah apel.","Buatkan resep jus buah apel."],"ai_response":"Buah apel adalah buah manis yang tumbuh di pohon kelapa dan mengandung banyak klorofil merah. Apel sangat kaya akan serat.","incorrect_phrases":["tumbuh di pohon kelapa","klorofil merah"]},"reward_xp":50},{"type":"quiz","question":"Jika AI 95% yakin, artinya...","choices":["Mungkin masih salah 5%","Pasti benar","AI sedang bercanda"],"answer_index":0,"hint":"Apakah yakin berarti benar?","explanation":"Keyakinan tinggi bukan jaminan benar. AI bisa sangat yakin tapi tetap salah!","reward_xp":20}]'::jsonb),
      ('ai-can-be-wrong', 'ai-ethics-course', 'ai-limitations', 1, 'en', 'AI Can Be Wrong', 'AI isn''t always right — even when it''s very confident.',
        '[{"type":"text","markdown":"AI isn''t always right! Sometimes AI is very confident but still wrong. That''s why we should always think critically when using AI.\\n\\nFor example, AI might think a pizza is a coin because both are round and yellow — with 99% confidence!"},{"type":"callout","style":"warning","markdown":"AI that''s 99% confident can still be wrong. Example: AI might mistake a pizza for a coin because both are round and yellow!"},{"type":"widget","widget_type":"prompt_evaluator","config":{"scenario":"Asking AI about apples","prompt_options":["Explain what an apple is and its nutrients.","Write a short poem about apples.","Create a recipe for apple juice."],"ai_response":"An apple is a sweet fruit that grows on coconut trees and contains lots of red chlorophyll. Apples are very rich in fiber.","incorrect_phrases":["grows on coconut trees","red chlorophyll"]},"reward_xp":50},{"type":"quiz","question":"If AI is 95% confident, it means...","choices":["Could still be wrong 5% of the time","Definitely correct","AI is joking"],"answer_index":0,"hint":"Does confident mean correct?","explanation":"High confidence is no guarantee of correctness. AI can be very confident and still wrong!","reward_xp":20}]'::jsonb),

      -- bias-in-ai
      ('bias-in-ai', 'ai-ethics-course', 'ai-limitations', 2, 'id', 'Bias dalam AI', 'Belajar bagaimana data latih yang bias membuat AI menebak dengan salah.',
        '[{"type":"text","markdown":"AI hanya sepintar data latih yang kita berikan. Jika kita hanya melatih AI menggunakan Apel berwarna merah, ia tidak akan tahu bahwa Apel hijau juga merupakan Apel! Ini disebut dengan **bias** dalam AI."},{"type":"widget","widget_type":"bias_game","config":{"target_class":"Apel","biased_background":"Merah","items":[{"id":1,"image_url":"https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=150","label":"Apel","background":"Merah","is_biased":true},{"id":2,"image_url":"https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?w=150","label":"Apel","background":"Merah","is_biased":true},{"id":3,"image_url":"https://images.unsplash.com/photo-1550258114-28ab25db93cd?w=150","label":"Nanas","background":"Putih","is_biased":false},{"id":4,"image_url":"https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?w=150","label":"Apel","background":"Hijau","is_biased":false},{"id":5,"image_url":"https://images.unsplash.com/photo-1603052875302-d376b7c0638a?w=150","label":"Tomat","background":"Hijau","is_biased":false}]},"reward_xp":50},{"type":"quiz","question":"Apa itu bias dalam AI?","choices":["AI membuat tebakan yang tidak adil karena data latih yang tidak seimbang","AI kehabisan daya baterai","AI terlalu cepat belajar"],"answer_index":0,"hint":"Pikirkan contoh apel merah vs apel hijau.","explanation":"Bias terjadi ketika data latih tidak bervariasi atau tidak seimbang, sehingga AI membuat generalisasi yang salah.","reward_xp":20}]'::jsonb),
      ('bias-in-ai', 'ai-ethics-course', 'ai-limitations', 2, 'en', 'Bias in AI', 'Learn how biased training data makes AI make incorrect predictions.',
        '[{"type":"text","markdown":"AI is only as smart as the training data we provide. If we only train AI using red apples, it won''t know that green apples are also apples! This is called **bias** in AI."},{"type":"widget","widget_type":"bias_game","config":{"target_class":"Apple","biased_background":"Red","items":[{"id":1,"image_url":"https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=150","label":"Apple","background":"Red","is_biased":true},{"id":2,"image_url":"https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?w=150","label":"Apple","background":"Red","is_biased":true},{"id":3,"image_url":"https://images.unsplash.com/photo-1550258114-28ab25db93cd?w=150","label":"Pineapple","background":"White","is_biased":false},{"id":4,"image_url":"https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?w=150","label":"Apple","background":"Green","is_biased":false},{"id":5,"image_url":"https://images.unsplash.com/photo-1603052875302-d376b7c0638a?w=150","label":"Tomato","background":"Green","is_biased":false}]},"reward_xp":50},{"type":"quiz","question":"What is bias in AI?","choices":["AI makes unfair predictions due to unbalanced training data","AI runs out of battery","AI learns too fast"],"answer_index":0,"hint":"Think about the red vs green apple example.","explanation":"Bias occurs when training data is not diverse or balanced, leading AI to make incorrect generalizations.","reward_xp":20}]'::jsonb),

      -- data-privacy-ethics
      ('data-privacy-ethics', 'ai-ethics-course', 'ai-limitations', 3, 'id', 'Keamanan Data & Privasi Kita', 'Belajar pentingnya menyaring izin akses aplikasi di HP kita agar data pribadi tidak disalahgunakan.',
        '[{"type":"text","markdown":"AI membutuhkan banyak data untuk belajar. Namun, kadang aplikasi atau AI meminta data pribadi yang tidak mereka butuhkan!\\n\\nKita harus menjadi **Data Detective** yang kritis: periksa izin akses aplikasi (seperti kamera, lokasi, kontak) dan tolak jika tidak masuk akal (misalnya game offline meminta akses daftar kontak ponselmu)."},{"type":"callout","style":"fun_fact","markdown":"Menjaga privasi data adalah pilar utama etika AI yang bertanggung jawab (*Responsible AI*). Data pribadi kita adalah hak kita sepenuhnya."},{"type":"widget","widget_type":"privacy_auditor","config":{"apps":[{"name":"Kalkulator Pintar AI","requested_permissions":["Kalkulasi angka","Lokasi presisi GPS","Daftar Kontak"],"is_suspicious":true,"reason":"Aplikasi kalkulator tidak membutuhkan GPS dan daftar kontak untuk berhitung."},{"name":"Edit Foto Lucu AI","requested_permissions":["Akses Galeri/Foto","Kamera"],"is_suspicious":false,"reason":"Wajar jika editor foto membutuhkan akses kamera dan galeri."}]},"reward_xp":50},{"type":"quiz","question":"Mengapa kita harus berhati-hati memberikan izin data pribadi ke aplikasi AI?","choices":["Agar data pribadi tidak disalahgunakan untuk melacak atau mengiklankan sesuatu secara diam-diam","Karena AI tidak suka data","Agar memori ponsel kita tidak cepat penuh"],"answer_index":0,"hint":"Pikirkan tentang keamanan dan penyalahgunaan identitas diri.","explanation":"Membatasi izin akses aplikasi menjaga data pribadi kita tetap aman dan mencegah perusahaan menyalahgunakan data tersebut.","reward_xp":20}]'::jsonb),
      ('data-privacy-ethics', 'ai-ethics-course', 'ai-limitations', 3, 'en', 'Data Security & Our Privacy', 'Learn the importance of managing app permissions to protect our personal data from misuse.',
        '[{"type":"text","markdown":"AI requires lots of data to learn. However, sometimes apps or AI systems request personal data that they don''t actually need!\\n\\nWe must act as critical **Data Detectives**: check app access permissions (like camera, location, contacts) and reject them if they don''t make sense (for example, an offline game asking for your contacts list)."},{"type":"callout","style":"fun_fact","markdown":"Protecting data privacy is a central pillar of Responsible AI ethics. Our personal data is completely our own right."},{"type":"widget","widget_type":"privacy_auditor","config":{"apps":[{"name":"AI Smart Calculator","requested_permissions":["Calculate math","Precise GPS Location","Contacts List"],"is_suspicious":true,"reason":"A calculator app does not need GPS or contacts list to perform math calculations."},{"name":"AI Photo Editor","requested_permissions":["Gallery Access","Camera Access"],"is_suspicious":false,"reason":"It is normal for a photo editor to request camera and gallery permissions."}]},"reward_xp":50},{"type":"quiz","question":"Why should we be careful when granting personal data permissions to AI apps?","choices":["To prevent our personal data from being misused to track or target ads at us secretly","Because AI does not like data","To keep our phone storage from filling up too quickly"],"answer_index":0,"hint":"Think about personal safety and misuse of your identity.","explanation":"Limiting app permissions keeps our private data secure and prevents companies from misusing our profile.","reward_xp":20}]'::jsonb),

      -- spot-the-fake-deepfakes
      ('spot-the-fake-deepfakes', 'ai-ethics-course', 'ai-limitations', 4, 'id', 'Melihat yang Palsu: Deepfakes & Hoaks AI', 'Belajar mendeteksi gambar, suara, atau video palsu hasil rekayasa AI Generatif secara kritis.',
        '[{"type":"text","markdown":"Generative AI sangat pintar meniru wajah dan suara manusia. Hasil rekayasa video atau foto palsu yang terlihat sangat nyata ini disebut **Deepfake**.\\n\\nKita tidak boleh langsung mempercayai apa yang kita lihat di internet! Kita harus kritis mengenali detail kecil yang janggal seperti bentuk telinga yang aneh, anting-anting yang tidak simetris, atau kedipan mata yang tidak wajar."},{"type":"callout","style":"fun_fact","markdown":"Kata ''Deepfake'' berasal dari gabungan kata ''Deep Learning'' (teknologi AI yang digunakan) dan ''Fake'' (palsu)."},{"type":"widget","widget_type":"spot_the_fake","config":{"items":[{"id":1,"image_url":"https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=200","is_fake":false,"clue":"Foto asli dengan detail pencahayaan alami."},{"id":2,"image_url":"https://images.unsplash.com/photo-1527474305487-b87b222841cc?w=200","is_fake":true,"clue":"Kacamata menyatu dengan kulit pipi dan latar belakang berlekuk tidak wajar."}]},"reward_xp":50},{"type":"quiz","question":"Apa salah satu ciri gambar wajah hasil rekayasa AI (Deepfake) yang belum sempurna?","choices":["Detail anting-anting atau latar belakang yang tampak janggal dan tidak konsisten","Gambar selalu berwarna hitam putih","Gambar tidak memiliki piksel sama sekali"],"answer_index":0,"hint":"Cari keanehan pada detail kecil yang sering luput dari perhatian model AI.","explanation":"AI sering kesulitan membuat anting-anting yang simetris kiri-kanan atau menggambar latar belakang bergaris lurus tanpa melengkung aneh.","reward_xp":20}]'::jsonb),
      ('spot-the-fake-deepfakes', 'ai-ethics-course', 'ai-limitations', 4, 'en', 'Spotting the Fake: Deepfakes & AI Hoaxes', 'Learn how to critically detect fake images, audio, or videos generated by AI.',
        '[{"type":"text","markdown":"Generative AI is very good at mimicking human faces and voices. These realistic but fake videos or photos are called **Deepfakes**.\\n\\nWe shouldn''t believe everything we see on the internet! We must critically check small, odd details like weird ear shapes, asymmetrical earrings, or unnatural blinking."},{"type":"callout","style":"fun_fact","markdown":"The word ''Deepfake'' comes from a combination of ''Deep Learning'' (the underlying AI technology) and ''Fake''."},{"type":"widget","widget_type":"spot_the_fake","config":{"items":[{"id":1,"image_url":"https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=200","is_fake":false,"clue":"Real photo with natural lighting details."},{"id":2,"image_url":"https://images.unsplash.com/photo-1527474305487-b87b222841cc?w=200","is_fake":true,"clue":"Glasses blend into the cheek skin and the background has unnatural curves."}]},"reward_xp":50},{"type":"quiz","question":"What is one sign of an imperfect AI-generated face (Deepfake)?","choices":["Earrings or background details that look glitched and inconsistent","The image is always in black and white","The image has no pixels at all"],"answer_index":0,"hint":"Look for glitches in tiny details that the AI model might miss.","explanation":"AI often struggles to generate symmetric earrings or straight lines in the background without warp artifacts.","reward_xp":20}]'::jsonb),

      -- recommendation-systems
      ('recommendation-systems', 'ai-ethics-course', 'ai-recommendation', 1, 'id', 'Sistem Rekomendasi', 'Bagaimana YouTube dan TikTok menebak video kesukaanmu menggunakan data minat.',
        '[{"type":"text","markdown":"Pernahkah kamu heran mengapa beranda YouTube atau TikTok-mu penuh dengan video yang sangat kamu sukai? Itu adalah kerja **Sistem Rekomendasi AI**!\\n\\nAI mengamati riwayat tontonanmu, menyimpulkan minatmu, lalu membandingkannya dengan jutaan orang lain yang memiliki minat serupa. Metode ini disebut **Collaborative Filtering**."},{"type":"callout","style":"fun_fact","markdown":"Sistem rekomendasi sangat krusial! Lebih dari 70% video yang ditonton di YouTube berasal dari rekomendasi otomatis AI."},{"type":"widget","widget_type":"recommendation_engine","config":{"profiles":[{"id":"budi","name":"Budi","interests":["Sains","Luar Angkasa"]},{"id":"siti","name":"Siti","interests":["Kucing","Hewan Lucu"]},{"id":"andi","name":"Andi","interests":["Olahraga","Sepak Bola"]}],"videos":[{"id":"v1","title":"Misteri Planet Mars","category":"Sains","target_profile":"budi"},{"id":"v2","title":"Kompilasi Kucing Lucu","category":"Hewan Lucu","target_profile":"siti"},{"id":"v3","title":"Gol Terbaik Liga Inggris","category":"Olahraga","target_profile":"andi"},{"id":"v4","title":"Bagaimana Roket Bekerja","category":"Sains","target_profile":"budi"}]},"reward_xp":50},{"type":"quiz","question":"Bagaimana AI merekomendasikan video baru padamu?","choices":["Dengan mencocokkan video baru dengan minat tontonanmu sebelumnya","Memilih video secara acak","Hanya merekomendasikan video terpopuler saja"],"answer_index":0,"hint":"AI mempelajari pola minat dan riwayat tontonanmu.","explanation":"Sistem rekomendasi AI menganalisis minatmu dan merekomendasikan konten baru yang sesuai dengan ketertarikanmu sebelumnya.","reward_xp":20}]'::jsonb),
      ('recommendation-systems', 'ai-ethics-course', 'ai-recommendation', 1, 'en', 'Recommendation Systems', 'How YouTube and TikTok predict videos you like using interest data.',
        '[{"type":"text","markdown":"Have you ever wondered why your YouTube or TikTok homepage is filled with videos you love? That is the work of **AI Recommendation Systems**!\\n\\nAI observes your watch history, infers your interests, and compares them with millions of other users who share similar interests. This method is called **Collaborative Filtering**."},{"type":"callout","style":"fun_fact","markdown":"Recommendation systems are crucial! Over 70% of videos watched on YouTube come from automated AI recommendations."},{"type":"widget","widget_type":"recommendation_engine","config":{"profiles":[{"id":"budi","name":"Budi","interests":["Science","Outer Space"]},{"id":"siti","name":"Siti","interests":["Cats","Cute Animals"]},{"id":"andi","name":"Andi","interests":["Sports","Football"]}],"videos":[{"id":"v1","title":"Mysteries of Planet Mars","category":"Science","target_profile":"budi"},{"id":"v2","title":"Cute Kittens Compilation","category":"Cute Animals","target_profile":"siti"},{"id":"v3","title":"Best English League Goals","category":"Sports","target_profile":"andi"},{"id":"v4","title":"How Rockets Work","category":"Science","target_profile":"budi"}]},"reward_xp":50},{"type":"quiz","question":"How does AI recommend new videos to you?","choices":["By matching new videos with your previous watch interests","By choosing videos randomly","By only recommending the most popular videos"],"answer_index":0,"hint":"AI studies your interest patterns and watch history.","explanation":"An AI recommendation system analyzes your interests and recommends new content that matches your previous preferences.","reward_xp":20}]'::jsonb),

      -- image-classification
      ('image-classification', 'image-classification-cnn', 'cnn-basics', 1, 'id', 'Klasifikasi Gambar', 'Cara AI mengenali apa yang ada di dalam foto.',
        '[{"type":"text","markdown":"**Klasifikasi gambar** adalah cara AI mengenali apa yang ada di dalam foto. AI melihat pola-pola seperti bentuk, warna, dan tekstur untuk menentukan nama benda tersebut."},{"type":"image","image_url":"https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600","caption":"AI melihat pola di gambar"},{"type":"widget","widget_type":"fruit_scanner","config":{},"reward_xp":50},{"type":"quiz","question":"Apa itu klasifikasi gambar?","choices":["AI memberi nama pada gambar","AI menggambar","AI merekam video"],"answer_index":0,"hint":"Apa yang terjadi saat kamu scan buah?","explanation":"Klasifikasi gambar adalah AI memberi label/nama pada gambar berdasarkan pola yang dikenali.","reward_xp":20}]'::jsonb),
      ('image-classification', 'image-classification-cnn', 'cnn-basics', 1, 'en', 'Image Classification', 'How AI recognizes what''s in a photo.',
        '[{"type":"text","markdown":"**Image classification** is how AI recognizes what''s in a photo. AI looks for patterns like shapes, colors, and textures to identify objects."},{"type":"image","image_url":"https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600","caption":"AI looks for patterns in images"},{"type":"widget","widget_type":"fruit_scanner","config":{},"reward_xp":50},{"type":"quiz","question":"What is image classification?","choices":["AI names what''s in a picture","AI draws pictures","AI records video"],"answer_index":0,"hint":"What happens when you scan a fruit?","explanation":"Image classification is AI labeling what''s in an image based on patterns it recognizes.","reward_xp":20}]'::jsonb),

      -- how-computers-see-pixels
      ('how-computers-see-pixels', 'image-classification-cnn', 'cnn-basics', 2, 'id', 'Bagaimana Komputer Melihat Gambar?', 'Membuka rahasia piksel warna RGB (Red, Green, Blue) yang membentuk gambar di layar komputer.',
        '[{"type":"text","markdown":"Mata kita melihat keindahan apel merah secara langsung. Tapi, bagaimana dengan komputer?\\n\\nBagi komputer, gambar hanyalah sebuah kotak raksasa berisi angka-angka! Setiap kotak kecil disebut **piksel**, dan warnanya dibentuk oleh kombinasi tiga warna primer: **Red (Merah)**, **Green (Hijau)**, dan **Blue (Biru)** (RGB) dengan nilai antara 0 hingga 255."},{"type":"callout","style":"fun_fact","markdown":"Jika nilai Merah=255, Hijau=0, Biru=0, piksel tersebut berwarna merah menyala sempurna. Jika semuanya 255, warnanya menjadi Putih! Jika semuanya 0, warnanya menjadi Hitam."},{"type":"widget","widget_type":"pixel_zoom","config":{"image_url":"https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400","sample_pixels":[{"x":10,"y":10,"rgb":[255,0,0],"color_name":"Merah"},{"x":20,"y":20,"rgb":[0,255,0],"color_name":"Hijau"},{"x":30,"y":30,"rgb":[0,0,255],"color_name":"Biru"}]},"reward_xp":50},{"type":"quiz","question":"Komputer melihat warna gambar sebagai kumpulan angka dari tiga warna primer, yaitu...","choices":["Red, Green, Blue (RGB)","Cyan, Magenta, Yellow (CMY)","Black, White, Grey"],"answer_index":0,"hint":"Tiga warna primer layar digital.","explanation":"RGB (Red, Green, Blue) adalah model warna standar untuk layar digital di mana kombinasi ketiga warna ini menghasilkan berbagai warna lainnya.","reward_xp":20}]'::jsonb),
      ('how-computers-see-pixels', 'image-classification-cnn', 'cnn-basics', 2, 'en', 'How Computers See Images', 'Reveal the secrets of RGB (Red, Green, Blue) color pixels that make up images on computer screens.',
        '[{"type":"text","markdown":"Our eyes see a red apple directly. But what about computers?\\n\\nTo a computer, an image is just a giant grid of numbers! Each tiny square is called a **pixel**, and its color is made by combining three primary colors: **Red**, **Green**, and **Blue** (RGB) with values from 0 to 255."},{"type":"callout","style":"fun_fact","markdown":"If Red=255, Green=0, Blue=0, the pixel is bright red. If all are 255, it is White! If all are 0, it is Black."},{"type":"widget","widget_type":"pixel_zoom","config":{"image_url":"https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400","sample_pixels":[{"x":10,"y":10,"rgb":[255,0,0],"color_name":"Red"},{"x":20,"y":20,"rgb":[0,255,0],"color_name":"Green"},{"x":30,"y":30,"rgb":[0,0,255],"color_name":"Blue"}]},"reward_xp":50},{"type":"quiz","question":"Computers see image colors as a grid of numbers from three primary colors, namely...","choices":["Red, Green, Blue (RGB)","Cyan, Magenta, Yellow (CMY)","Black, White, Grey"],"answer_index":0,"hint":"The three primary colors of digital screens.","explanation":"RGB (Red, Green, Blue) is the standard color model for digital screens, where combinations of these three colors produce all other colors.","reward_xp":20}]'::jsonb)
    ;`)

    return { ok: true }
  } catch (err) {
    return { ok: false, error: err.message }
  } finally {
    if (client) {
      await client.end()
    }
  }
}
